positibe_mailing_mail:
    resource: "@PositibeMailingBundle/Resources/config/routing/mail.yml"
    prefix:   /mails

positibe_mailing_template:
    resource: "@PositibeMailingBundle/Resources/config/routing/template.yml"
    prefix:   /templates
