sylius_resource:
    resources:
        positibe.template:
            driver: doctrine/orm
            templates: PositibeMailingBundle:Template
            classes:
                model: Positibe\Bundle\MailingBundle\Entity\Template
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form: Positibe\Bundle\MailingBundle\Form\Type\TemplateFormType
        positibe.mail:
            driver: doctrine/orm
            templates: PositibeMailingBundle:Mail
            classes:
                model: Positibe\Bundle\MailingBundle\Entity\Mail
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\MailingBundle\Repository\MailRepository
#                form:
#                    default: PositibeMailingBundle\Form\Type\MailFormType
