<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\MailingBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;

/**
 * Class TemplateFormType
 * @package Positibe\Bundle\MailingBundle\Form\Type
 */
class TemplateFormType extends AbstractType
{
    protected $checker;

    public function __construct(AuthorizationChecker $authorizationChecker)
    {
        $this->checker = $authorizationChecker;
    }


    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'subject',
                null,
                array('label' => 'Asunto:')
            )
            ->add(
                'body',
                null,
                array(
                    'label' => 'Cuerpo:',
                    'attr' => array(
                        'rows' => 10
                    )
                )
            )
            ->add(
                'description',
                null,
                array(
                    'label' => 'Descripción:',
                    'required' => false,
                )
            )
            ->add(
                'image',
                'positibe_media_type',
                array(
                    'label' => 'Imagen:'
                )
            );

        if ($this->checker->isGranted('ROLE_ADMIN') || $options['data'] === null || $options['data']->getId() === null) {
            $builder
                ->add(
                    'code',
                    null,
                    array('label' => 'Nombre (Código):')
                )//Este código se genera automáticamente o se crea con la plantilla y no debe modificarse
//            ->add('public',) //Si todos los usuarios lo puede ver
                ->add(
                    'deleteable',
                    null,
                    array(
                        'label' => 'Eliminable',
                        'required' => false,
                    )
                ) //Permite o no eliminar un template
//            ->add('availableRoles', 'choice') //Los roles que tienen acceso a esta plantilla
            ;
        }
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\MailingBundle\Entity\Template'
            )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'positibe_template';
    }
}
