positibe_template_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: positibe.controller.template:createAction
        _sylius:
            redirect:
                route: positibe_template_update
                parameters: {id: resource.id}

positibe_template_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: positibe.controller.template:showAction

positibe_template_preview:
    path: /{id}/preview
    methods: [GET]
    defaults:
        _controller: positibe.controller.template:showAction
        _sylius:
            template: PositibeMailingBundle:Template:preview.html.twig

positibe_template_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: positibe.controller.template:updateAction
        _sylius:
            redirect:
                route: positibe_template_update
                parameters: {id: resource.id}

positibe_template_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: positibe.controller.template:deleteAction
        _sylius:
            criteria:
                code: $code
                deleteable: true
            redirect:
                route: positibe_template_index
                parameters: {}

positibe_template_index:
    path: /
    methods: [GET]
    defaults:
        _controller: positibe.controller.template:indexAction
        _sylius:
            sortable: true
